########## O QUE SÃO OPERDORES ########
# SÃO EXPRESSÕES MATEMÁTICAS USADAS NAS LINGUÁGENS #


## OPERADORES ARITMÉTICOS ##
# + (ADIÇÃO) , - (SUBTRAÇÃO), / (DIVISÃO), * (MULTIPLICAÇÃO)


## OPERADORES RECIONAIS ##
# == (IGUAL A), != (DIFERENTE DE), > (MAIOR QUE), < (MENOR QUE), >= (MAIOR OU IGUAL), <= (MENOR OU IGUAL)


## OPERADORES LÓGICOS ## 
# && (AND LÓGICO), ||(OR LÓGICO), | (NOT LÓGICO)

## OPERADORES DE ATRIBUIÇÃO ##
# = (ATRIBUIÇÃO), += (ADIÇÃO E ATRIBUIÇÃO), -= (SUBTRAÇÃO E ATRIBUIÇÃO), *= (MULTIPLICAÇÃO E ATRIBUIÇÃO), /= (DIVISÃO E ATRIBUIÇÃO), %= (MÓDULO E ATRIBUIÇÃO)


## OPERADORES DE ICREMENTO E DECREMENTO ##
# ++ (INCREMENTO), -- (DESCREMENTO)








